apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{ .Values.namespace }}
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: {{ .Values.client.image }}
        ports:
        - containerPort: {{ .Values.client.port }}
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            secretKeyRef:
              name: app-env-vars
              key: REACT_APP_API_URL
        - name: SERVER_SERVICE
          valueFrom:
            secretKeyRef:
              name: app-env-vars
              key: SERVER_SERVICE

