apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: {{ .Values.namespace }}
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: {{ .Values.server.image }}
        ports:
        - containerPort: {{ .Values.server.port }}
        env:
        - name: CLIENT_SERVICE
          valueFrom:
            secretKeyRef:
              name: app-env-vars
              key: CLIENT_SERVICE
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-env-vars
              key: MONGO_URI
        - name: CLIENT_URL
          valueFrom:
            secretKeyRef:
              name: app-env-vars
              key: CLIENT_URL

