apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc2
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.size }}
  storageClassName: {{ .Values.mongo.persistence.storageClassName }}

