apiVersion: v1
kind: Secret
metadata:
  name: app-env-vars
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SERVER_SERVICE: {{ .Values.client.env | index 0 | .value | b64enc | quote }}
  REACT_APP_API_URL: {{ .Values.client.env | index 1 | .value | b64enc | quote }}
  CLIENT_SERVICE: {{ .Values.server.env | index 0 | .value | b64enc | quote }}
  MONGO_URI: {{ .Values.server.env | index 1 | .value | b64enc | quote }}
  CLIENT_URL: {{ .Values.server.env | index 2 | .value | b64enc | quote }}

