apiVersion: v1
kind: Secret
metadata:
  name: app-env-vars
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SERVER_SERVICE: {{ .Values.client.env[0].value | b64enc }}
  REACT_APP_API_URL: {{ .Values.client.env[1].value | b64enc }}
  CLIENT_SERVICE: {{ .Values.server.env[0].value | b64enc }}
  MONGO_URI: {{ .Values.server.env[1].value | b64enc }}
  CLIENT_URL: {{ .Values.server.env[2].value | b64enc }}

