apiVersion: v1
kind: Secret
metadata:
  name: app-env-vars
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  REACT_APP_API_URL: {{ .Values.client.env.REACT_APP_API_URL | b64enc | quote }}
  CLIENT_SERVICE: {{ .Values.server.env.CLIENT_SERVICE | b64enc | quote }}
  MONGO_URI: {{ .Values.server.env.MONGO_URI | b64enc | quote }}
  CLIENT_URL: {{ .Values.server.env.CLIENT_URL | b64enc | quote }}
