apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: helm-movie-app
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: server
  type: LoadBalancer  # This makes the service accessible from the external network

