apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.client.serviceType }}  # LoadBalancer
  ports:
  - port: 3000                           # Exposed port for the LoadBalancer
    targetPort: {{ .Values.client.port }} # Container port (3000)
  selector:
    app: client

