namespace: argo-helm-movie-app

client:
  image: amitnai/client:latest
  port: 3000
  serviceType: LoadBalancer
  env:
    - name: SERVER_SERVICE
      value: "http://4.157.9.5:5000"
    - name: REACT_APP_API_URL
      value: "http://4.157.9.5:5000/api"

server:
  image: amitnai/server:latest
  port: 5000
  serviceType: LoadBalancer
  env:
    - name: CLIENT_SERVICE
      value: "http://74.179.210.22:3000"
    - name: MONGO_URI
      value: "mongodb://mongo:27017/cinema"
    - name: CLIENT_URL
      value: "http://74.179.210.22:3000"

mongo:
  image: amitnai/mongo:latest
  port: 27017
  serviceType: ClusterIP

