namespace: argo-helm-movie-app

client:
  image: amitnai/client:latest
  port: 3000
  serviceType: LoadBalancer
  replicas: 2  # Initial replicas for client
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  env:
    SERVER_SERVICE: "http://135.237.75.185:5000"
    REACT_APP_API_URL: "http://135.237.75.185:5000/api"

server:
  image: amitnai/server:latest
  port: 5000
  serviceType: LoadBalancer
  replicas: 2  # Initial replicas for server
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi
  env:
    CLIENT_SERVICE: "http://57.152.52.91:3000"
    MONGO_URI: "mongodb://mongo:27017/cinema"
    CLIENT_URL: "http://57.152.52.91:3000"

mongo:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
  port: 27017
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: vault-storage-class
  statefulset:
    enabled: true

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuThreshold: 70

