namespace: argo-helm-movie-app

client:
  image: amitnai/client:latest
  port: 3000
  serviceType: LoadBalancer
  env:
    SERVER_SERVICE: "http://135.237.75.185:5000"
    REACT_APP_API_URL: "http://135.237.75.185:5000/api"

server:
  image: amitnai/server:latest
  port: 5000
  serviceType: LoadBalancer
  env:
    CLIENT_SERVICE: "http://57.152.52.91:3000"
    MONGO_URI: "mongodb://mongo:27017/cinema"
    CLIENT_URL: "http://57.152.52.91:3000"

mongo:
  image: amitnai/mongo:latest
  port: 27017
  serviceType: ClusterIP

